const icons = {
  home: require("../assets/icons/home.png"),
  change: require("../assets/icons/change.png"),
  calendar: require("../assets/icons/calendar.png"),
  tooth: require("../assets/icons/tooth.png"),
  scan: require("../assets/icons/scan.png"),
  menu: require("../assets/icons/hamburger-menu.png"),
  cart: require("../assets/icons/cart.png"),
  bell: require("../assets/icons/bell.png"),
  xButton: require("../assets/icons/x-button.png"),
  logo: require("../assets/icons/logo.png"),
  clearIcon: require("../assets/icons/clear-icon.png"),
  eye: require("../assets/icons/eye.png"),
  eyeSlash: require("../assets/icons/eye-slash.png"),
  refresh: require("../assets/icons/refresh.png"),
  search: require("../assets/icons/search.png"),
  next: require("../assets/icons/next.png"),
  nextIcon: require("../assets/icons/previous-icon.png"),
  previousIcon: require("../assets/icons/next-icon.png"),
  arrowLeft: require("../assets/icons/arrow-left.png"),
  arrowRight: require("../assets/icons/arrow-right.png"),
  arrowUp: require("../assets/icons/arrow-up.png"),
  arrowDown: require("../assets/icons/arrow-down.png"),
  check: require("../assets/icons/check.png"),
  catalog: require("../assets/icons/catalog.png"),
  doubleLeft: require("../assets/icons/double-left.png"),
  doubleRight: require("../assets/icons/double-right.png"),
  previous: require("../assets/icons/previous.png"),
  share: require("../assets/icons/share.png"),
  tickboxSelected: require("../assets/icons/tickbox-selected.png"),
  up: require("../assets/icons/up.png"),
  down: require("../assets/icons/down.png"),
  star: require("../assets/icons/star.png"),
  starSelect: require("../assets/icons/star-select.png"),
  searchClose: require("../assets/icons/search-close.png"),
  radioSelect: require("../assets/icons/radio-select.png"),
  radioUnselect: require("../assets/icons/radio-unselect.png"),
  xClose: require("../assets/icons/xclose.png"),
  checklistFixture: require("../assets/icons/checklist-fixture.png"),
  searchBackground: require("../assets/icons/search-background.png"),

  radioOff: require("../assets/icons/radio-off.png"),
  radioOn: require("../assets/icons/radio-on.png"),
  top: require("../assets/icons/top.png"),
  camera: require("../assets/icons/camera.png"),
  closeImage: require("../assets/icons/close-image.png"),
  doctor: require("../assets/icons/doctor.png"),
  nurse: require("../assets/icons/nurse.png"),
  plus: require("../assets/icons/plus.png"),
  minus: require("../assets/icons/minus.png"),

  starBigSelect: require("../assets/icons/star-big-select.png"),
  starBig: require("../assets/icons/star-big.png"),
  xImage: require("../assets/icons/x-image.png"),
  plusRectangle: require("../assets/icons/plus-rectangle.png"),
  info: require("../assets/icons/info.png"),
  profile: require("../assets/icons/profile.png"),
  markYellow: require("../assets/icons/mark-yellow.png"),
  clipBoard: require("../assets/icons/clipboard.png"),
  check2: require("../assets/icons/check2.png")
};

export default icons;
