export const tooth = {
  unselect11: require("../assets/tooth/unselect/unselect-11.png"),
  unselect12: require("../assets/tooth/unselect/unselect-12.png"),
  unselect13: require("../assets/tooth/unselect/unselect-13.png"),
  unselect14: require("../assets/tooth/unselect/unselect-14.png"),
  unselect15: require("../assets/tooth/unselect/unselect-15.png"),
  unselect16: require("../assets/tooth/unselect/unselect-16.png"),
  unselect17: require("../assets/tooth/unselect/unselect-17.png"),
  unselect18: require("../assets/tooth/unselect/unselect-18.png"),
  unselect21: require("../assets/tooth/unselect/unselect-21.png"),
  unselect22: require("../assets/tooth/unselect/unselect-22.png"),
  unselect23: require("../assets/tooth/unselect/unselect-23.png"),
  unselect24: require("../assets/tooth/unselect/unselect-24.png"),
  unselect25: require("../assets/tooth/unselect/unselect-25.png"),
  unselect26: require("../assets/tooth/unselect/unselect-26.png"),
  unselect27: require("../assets/tooth/unselect/unselect-27.png"),
  unselect28: require("../assets/tooth/unselect/unselect-28.png"),

  unselect31: require("../assets/tooth/unselect/unselect-31.png"),
  unselect32: require("../assets/tooth/unselect/unselect-32.png"),
  unselect33: require("../assets/tooth/unselect/unselect-33.png"),
  unselect34: require("../assets/tooth/unselect/unselect-34.png"),
  unselect35: require("../assets/tooth/unselect/unselect-35.png"),
  unselect36: require("../assets/tooth/unselect/unselect-36.png"),
  unselect37: require("../assets/tooth/unselect/unselect-37.png"),
  unselect38: require("../assets/tooth/unselect/unselect-38.png"),

  unselect41: require("../assets/tooth/unselect/unselect-41.png"),
  unselect42: require("../assets/tooth/unselect/unselect-42.png"),
  unselect43: require("../assets/tooth/unselect/unselect-43.png"),
  unselect44: require("../assets/tooth/unselect/unselect-44.png"),
  unselect45: require("../assets/tooth/unselect/unselect-45.png"),
  unselect46: require("../assets/tooth/unselect/unselect-46.png"),
  unselect47: require("../assets/tooth/unselect/unselect-47.png"),
  unselect48: require("../assets/tooth/unselect/unselect-48.png"),
};

export const toothSelectBlue = {
  selectBlue11: require("../assets/tooth/selectBlue/select-blue-11.png"),
  selectBlue12: require("../assets/tooth/selectBlue/select-blue-12.png"),
  selectBlue13: require("../assets/tooth/selectBlue/select-blue-13.png"),
  selectBlue14: require("../assets/tooth/selectBlue/select-blue-14.png"),
  selectBlue15: require("../assets/tooth/selectBlue/select-blue-15.png"),
  selectBlue16: require("../assets/tooth/selectBlue/select-blue-16.png"),
  selectBlue17: require("../assets/tooth/selectBlue/select-blue-17.png"),
  selectBlue18: require("../assets/tooth/selectBlue/select-blue-18.png"),
  selectBlue21: require("../assets/tooth/selectBlue/select-blue-21.png"),
  selectBlue22: require("../assets/tooth/selectBlue/select-blue-22.png"),
  selectBlue23: require("../assets/tooth/selectBlue/select-blue-23.png"),
  selectBlue24: require("../assets/tooth/selectBlue/select-blue-24.png"),
  selectBlue25: require("../assets/tooth/selectBlue/select-blue-25.png"),
  selectBlue26: require("../assets/tooth/selectBlue/select-blue-26.png"),
  selectBlue27: require("../assets/tooth/selectBlue/select-blue-27.png"),
  selectBlue28: require("../assets/tooth/selectBlue/select-blue-28.png"),
  selectBlue31: require("../assets/tooth/selectBlue/select-blue-31.png"),
  selectBlue32: require("../assets/tooth/selectBlue/select-blue-32.png"),
  selectBlue33: require("../assets/tooth/selectBlue/select-blue-33.png"),
  selectBlue34: require("../assets/tooth/selectBlue/select-blue-34.png"),
  selectBlue35: require("../assets/tooth/selectBlue/select-blue-35.png"),
  selectBlue36: require("../assets/tooth/selectBlue/select-blue-36.png"),
  selectBlue37: require("../assets/tooth/selectBlue/select-blue-37.png"),
  selectBlue38: require("../assets/tooth/selectBlue/select-blue-38.png"),
  selectBlue41: require("../assets/tooth/selectBlue/select-blue-41.png"),
  selectBlue42: require("../assets/tooth/selectBlue/select-blue-42.png"),
  selectBlue43: require("../assets/tooth/selectBlue/select-blue-43.png"),
  selectBlue44: require("../assets/tooth/selectBlue/select-blue-44.png"),
  selectBlue45: require("../assets/tooth/selectBlue/select-blue-45.png"),
  selectBlue46: require("../assets/tooth/selectBlue/select-blue-46.png"),
  selectBlue47: require("../assets/tooth/selectBlue/select-blue-47.png"),
  selectBlue48: require("../assets/tooth/selectBlue/select-blue-48.png"),
};

export const toothSelectRed = {
  selectRed11: require("../assets/tooth/selectRed/select-red-11.png"),
  selectRed12: require("../assets/tooth/selectRed/select-red-12.png"),
  selectRed13: require("../assets/tooth/selectRed/select-red-13.png"),
  selectRed14: require("../assets/tooth/selectRed/select-red-14.png"),
  selectRed15: require("../assets/tooth/selectRed/select-red-15.png"),
  selectRed16: require("../assets/tooth/selectRed/select-red-16.png"),
  selectRed17: require("../assets/tooth/selectRed/select-red-17.png"),
  selectRed18: require("../assets/tooth/selectRed/select-red-18.png"),
  selectRed21: require("../assets/tooth/selectRed/select-red-21.png"),
  selectRed22: require("../assets/tooth/selectRed/select-red-22.png"),
  selectRed23: require("../assets/tooth/selectRed/select-red-23.png"),
  selectRed24: require("../assets/tooth/selectRed/select-red-24.png"),
  selectRed25: require("../assets/tooth/selectRed/select-red-25.png"),
  selectRed26: require("../assets/tooth/selectRed/select-red-26.png"),
  selectRed27: require("../assets/tooth/selectRed/select-red-27.png"),
  selectRed28: require("../assets/tooth/selectRed/select-red-28.png"),
  selectRed31: require("../assets/tooth/selectRed/select-red-31.png"),
  selectRed32: require("../assets/tooth/selectRed/select-red-32.png"),
  selectRed33: require("../assets/tooth/selectRed/select-red-33.png"),
  selectRed34: require("../assets/tooth/selectRed/select-red-34.png"),
  selectRed35: require("../assets/tooth/selectRed/select-red-35.png"),
  selectRed36: require("../assets/tooth/selectRed/select-red-36.png"),
  selectRed37: require("../assets/tooth/selectRed/select-red-37.png"),
  selectRed38: require("../assets/tooth/selectRed/select-red-38.png"),
  selectRed41: require("../assets/tooth/selectRed/select-red-41.png"),
  selectRed42: require("../assets/tooth/selectRed/select-red-42.png"),
  selectRed43: require("../assets/tooth/selectRed/select-red-43.png"),
  selectRed44: require("../assets/tooth/selectRed/select-red-44.png"),
  selectRed45: require("../assets/tooth/selectRed/select-red-45.png"),
  selectRed46: require("../assets/tooth/selectRed/select-red-46.png"),
  selectRed47: require("../assets/tooth/selectRed/select-red-47.png"),
  selectRed48: require("../assets/tooth/selectRed/select-red-48.png"),
};
