// fromDatabase if on database any teeth selected will be red color
// fromLocal if on user selected any teeth will be bluecolor

import { tooth, toothSelectBlue, toothSelectRed } from "configs/tooth";

export const Config = [
  {
    teeth: [
      {
        teethNo: 11,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 11",
        imageInfoUnselect: {
          image: tooth.unselect11,
          width: 31.5,
          height: 33.2,
          top: 0,
          left: -31.5,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue11,
          width: 31.5,
          height: 42.8,
          top: -10,
          left: -31.5,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed11,
          width: 31.5,
          height: 42.8,
          top: -10,
          left: -31.5,
        },
      },
      {
        teethNo: 21,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 21",
        imageInfoUnselect: {
          image: tooth.unselect21,
          width: 31.5,
          height: 33.2,
          top: 0,
          left: 0,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue21,
          width: 31.5,
          height: 42.8,
          top: -10,
          left: 0,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed21,
          width: 31.5,
          height: 42.8,
          top: -10,
          left: 0,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 12,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 12",
        imageInfoUnselect: {
          image: tooth.unselect12,
          width: 26,
          height: 27,
          top: 8,
          left: -57,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue12,
          width: 29,
          height: 35,
          top: -1,
          left: -59,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed12,
          width: 29,
          height: 35,
          top: -1,
          left: -59,
        },
      },
      {
        teethNo: 22,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 22",
        imageInfoUnselect: {
          image: tooth.unselect22,
          width: 26,
          height: 27,
          top: 8,
          left: 31,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue22,
          width: 29,
          height: 35,
          top: -1,
          left: 29,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed22,
          width: 29,
          height: 35,
          top: -1,
          left: 29,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 13,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 13",
        imageInfoUnselect: {
          image: tooth.unselect13,
          width: 30,
          height: 29,
          top: 21,
          left: -80,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue13,
          width: 36,
          height: 32,
          top: 18,
          left: -85,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed13,
          width: 36,
          height: 32,
          top: 18,
          left: -85,
        },
      },
      {
        teethNo: 23,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 23",
        imageInfoUnselect: {
          image: tooth.unselect23,
          width: 30,
          height: 29,
          top: 21,
          left: 50,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue23,
          width: 36,
          height: 32,
          top: 18,
          left: 50,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed23,
          width: 36,
          height: 32,
          top: 18,
          left: 50,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 14,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 14",
        imageInfoUnselect: {
          image: tooth.unselect14,
          width: 34,
          height: 28,
          top: 47,
          left: -95,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue14,
          width: 40,
          height: 30,
          top: 45,
          left: -100,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed14,
          width: 40,
          height: 30,
          top: 45,
          left: -100,
        },
      },
      {
        teethNo: 24,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 24",
        imageInfoUnselect: {
          image: tooth.unselect24,
          width: 34,
          height: 28,
          top: 47,
          left: 60,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue24,
          width: 40,
          height: 30,
          top: 45,
          left: 61,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed24,
          width: 40,
          height: 30,
          top: 45,
          left: 61,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 15,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 15",
        imageInfoUnselect: {
          image: tooth.unselect15,
          width: 35,
          height: 27,
          top: 72,
          left: -105,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue15,
          width: 41,
          height: 27,
          top: 72,
          left: -113,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed15,
          width: 41,
          height: 27,
          top: 72,
          left: -113,
        },
      },
      {
        teethNo: 25,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 25",
        imageInfoUnselect: {
          image: tooth.unselect25,
          width: 35,
          height: 27,
          top: 72,
          left: 71,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue25,
          width: 41,
          height: 27,
          top: 72,
          left: 71,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed25,
          width: 41,
          height: 27,
          top: 72,
          left: 71,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 16,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 16",
        imageInfoUnselect: {
          image: tooth.unselect16,
          width: 40,
          height: 42,
          top: 98,
          left: -115,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue16,
          width: 44,
          height: 42,
          top: 98,
          left: -119,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed16,
          width: 44,
          height: 42,
          top: 98,
          left: -119,
        },
      },
      {
        teethNo: 26,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 26",
        imageInfoUnselect: {
          image: tooth.unselect26,
          width: 40,
          height: 42,
          top: 98,
          left: 74,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue26,
          width: 44,
          height: 42,
          top: 98,
          left: 76,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed26,
          width: 44,
          height: 42,
          top: 98,
          left: 76,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 17,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 17",
        imageInfoUnselect: {
          image: tooth.unselect17,
          width: 33,
          height: 37,
          top: 135,
          left: -119,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue17,
          width: 41,
          height: 36,
          top: 135,
          left: -125,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed17,
          width: 41,
          height: 36,
          top: 135,
          left: -125,
        },
      },
      {
        teethNo: 27,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 27",
        imageInfoUnselect: {
          image: tooth.unselect27,
          width: 33,
          height: 37,
          top: 135,
          left: 85,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue27,
          width: 41,
          height: 36,
          top: 135,
          left: 86,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed27,
          width: 41,
          height: 36,
          top: 135,
          left: 86,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 18,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 18",
        imageInfoUnselect: {
          image: tooth.unselect18,
          width: 32,
          height: 30,
          top: 169,
          left: -125,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue18,
          width: 41,
          height: 30,
          top: 169,
          left: -133,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed18,
          width: 41,
          height: 30,
          top: 169,
          left: -133,
        },
      },
      {
        teethNo: 28,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 28",
        imageInfoUnselect: {
          image: tooth.unselect28,
          width: 32,
          height: 30,
          top: 169,
          left: 93,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue28,
          width: 41,
          height: 30,
          top: 169,
          left: 92,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed28,
          width: 41,
          height: 30,
          top: 169,
          left: 92,
        },
      },
    ],
  },

  //Teeth Bottom
  {
    teeth: [
      {
        teethNo: 48,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 48",
        imageInfoUnselect: {
          image: tooth.unselect48,
          width: 33,
          height: 35,
          top: 230,
          left: -125,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue48,
          width: 43,
          height: 35,
          top: 230,
          left: -133,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed48,
          width: 43,
          height: 35,
          top: 230,
          left: -133,
        },
      },
      {
        teethNo: 38,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 38",
        imageInfoUnselect: {
          image: tooth.unselect38,
          width: 33,
          height: 35,
          top: 230,
          left: 92,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue38,
          width: 43,
          height: 35,
          top: 230,
          left: 92,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed38,
          width: 43,
          height: 35,
          top: 230,
          left: 92,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 47,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 47",
        imageInfoUnselect: {
          image: tooth.unselect47,
          width: 37,
          height: 38,
          top: 264,
          left: -115,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue47,
          width: 47,
          height: 38,
          top: 264,
          left: -125,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed47,
          width: 47,
          height: 38,
          top: 264,
          left: -125,
        },
      },
      {
        teethNo: 37,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 37",
        imageInfoUnselect: {
          image: tooth.unselect37,
          width: 37,
          height: 38,
          top: 264,
          left: 78,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue37,
          width: 47,
          height: 38,
          top: 264,
          left: 78,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed37,
          width: 47,
          height: 38,
          top: 264,
          left: 78,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 46,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 46",
        imageInfoUnselect: {
          image: tooth.unselect46,
          width: 39,
          height: 41,
          top: 300,
          left: -104,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue46,
          width: 51,
          height: 41,
          top: 300,
          left: -115,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed46,
          width: 51,
          height: 41,
          top: 300,
          left: -115,
        },
      },
      {
        teethNo: 36,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 36",
        imageInfoUnselect: {
          image: tooth.unselect36,
          width: 39,
          height: 41,
          top: 300,
          left: 65,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue36,
          width: 51,
          height: 41,
          top: 300,
          left: 65,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed36,
          width: 51,
          height: 41,
          top: 300,
          left: 65,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 45,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 45",
        imageInfoUnselect: {
          image: tooth.unselect45,
          width: 32,
          height: 26,
          top: 337,
          left: -88,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue45,
          width: 43,
          height: 26,
          top: 337,
          left: -99,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed45,
          width: 43,
          height: 26,
          top: 337,
          left: -99,
        },
      },
      {
        teethNo: 35,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 35",
        imageInfoUnselect: {
          image: tooth.unselect35,
          width: 32,
          height: 26,
          top: 337,
          left: 56,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue35,
          width: 43,
          height: 26,
          top: 337,
          left: 56,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed35,
          width: 43,
          height: 26,
          top: 337,
          left: 56,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 44,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 44",
        imageInfoUnselect: {
          image: tooth.unselect44,
          width: 27,
          height: 24,
          top: 361,
          left: -75,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue44,
          width: 38,
          height: 24,
          top: 361,
          left: -85,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed44,
          width: 38,
          height: 24,
          top: 361,
          left: -85,
        },
      },
      {
        teethNo: 34,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 34",
        imageInfoUnselect: {
          image: tooth.unselect34,
          width: 27,
          height: 24,
          top: 361,
          left: 47,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue34,
          width: 38,
          height: 24,
          top: 361,
          left: 47,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed34,
          width: 38,
          height: 24,
          top: 361,
          left: 47,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 43,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 43",
        imageInfoUnselect: {
          image: tooth.unselect43,
          width: 23,
          height: 24,
          top: 380,
          left: -60,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue43,
          width: 31,
          height: 33,
          top: 380,
          left: -67,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed43,
          width: 31,
          height: 33,
          top: 380,
          left: -67,
        },
      },
      {
        teethNo: 33,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 33",
        imageInfoUnselect: {
          image: tooth.unselect33,
          width: 23,
          height: 24,
          top: 380,
          left: 37,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue33,
          width: 31,
          height: 33,
          top: 380,
          left: 38,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed33,
          width: 31,
          height: 33,
          top: 380,
          left: 38,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 42,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 42",
        imageInfoUnselect: {
          image: tooth.unselect42,
          width: 21,
          height: 25,
          top: 394,
          left: -40,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue42,
          width: 25,
          height: 35,
          top: 394,
          left: -44,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed42,
          width: 25,
          height: 35,
          top: 394,
          left: -44,
        },
      },
      {
        teethNo: 32,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 32",
        imageInfoUnselect: {
          image: tooth.unselect32,
          width: 21,
          height: 25,
          top: 394,
          left: 20,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue32,
          width: 25,
          height: 35,
          top: 394,
          left: 22,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed32,
          width: 25,
          height: 35,
          top: 394,
          left: 22,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 41,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 41",
        imageInfoUnselect: {
          image: tooth.unselect41,
          width: 19,
          height: 24,
          top: 398,
          left: -17,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue41,
          width: 19,
          height: 35,
          top: 398,
          left: -19,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed41,
          width: 19,
          height: 35,
          top: 398,
          left: -19,
        },
      },
      {
        teethNo: 31,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 31",
        imageInfoUnselect: {
          image: tooth.unselect31,
          width: 19,
          height: 24,
          top: 398,
          left: 3,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue31,
          width: 19,
          height: 35,
          top: 398,
          left: 3,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed31,
          width: 19,
          height: 35,
          top: 398,
          left: 3,
        },
      },
    ],
  },
];
