// fromDatabase if on database any teeth selected will be red color
// fromLocal if on user selected any teeth will be bluecolor

import { tooth, toothSelectBlue, toothSelectRed } from "configs/tooth";

export const Config = [
  {
    teeth: [
      {
        teethNo: 11,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 11",
        imageInfoUnselect: {
          image: tooth.unselect11,
          top: 0,
          left: 152.9,
          width: 24.9,
          height: 26.2,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue11,
          top: 0,
          left: 152.9,
          width: 24.9,
          height: 26.2,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed11,
          top: 0,
          left: 152.9,
          width: 24.9,
          height: 26.2,
        },
      },
      {
        teethNo: 21,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 21",
        imageInfoUnselect: {
          image: tooth.unselect21,
          top: 0,
          left: 178,
          width: 24.9,
          height: 26.2,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue21,
          top: 0,
          left: 178,
          width: 24.9,
          height: 26.2,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed21,
          top: 0,
          left: 178,
          width: 24.9,
          height: 26.2,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 12,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 12",
        imageInfoUnselect: {
          image: tooth.unselect12,
          top: 8,
          left: 133,
          width: 21.1,
          height: 21.8,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue12,
          top: 8,
          left: 133,
          width: 21.1,
          height: 21.8,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed12,
          top: 8,
          left: 133,
          width: 21.1,
          height: 21.8,
        },
      },
      {
        teethNo: 22,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 22",
        imageInfoUnselect: {
          image: tooth.unselect22,
          top: 8,
          left: 201,
          width: 21.1,
          height: 21.8,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue22,
          top: 8,
          left: 201,
          width: 21.1,
          height: 21.8,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed22,
          top: 8,
          left: 201,
          width: 21.1,
          height: 21.8,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 13,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 13",
        imageInfoUnselect: {
          image: tooth.unselect13,
          top: 20,
          left: 115,
          width: 23.8,
          height: 22.9,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue13,
          top: 20,
          left: 115,
          width: 23.8,
          height: 22.9,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed13,
          top: 20,
          left: 115,
          width: 23.8,
          height: 22.9,
        },
      },
      {
        teethNo: 23,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 23",
        imageInfoUnselect: {
          image: tooth.unselect23,
          top: 20,
          left: 216,
          width: 23.8,
          height: 22.9,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue23,
          top: 20,
          left: 216,
          width: 23.8,
          height: 22.9,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed23,
          top: 20,
          left: 216,
          width: 23.8,
          height: 22.9,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 14,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 14",
        imageInfoUnselect: {
          image: tooth.unselect14,
          top: 41,
          left: 101,
          width: 27.2,
          height: 22.5,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue14,
          top: 41,
          left: 101,
          width: 27.2,
          height: 22.5,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed14,
          top: 41,
          left: 101,
          width: 27.2,
          height: 22.5,
        },
      },
      {
        teethNo: 24,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 24",
        imageInfoUnselect: {
          image: tooth.unselect24,
          top: 41,
          left: 227,
          width: 27.2,
          height: 22.5,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue24,
          top: 41,
          left: 227,
          width: 27.2,
          height: 22.5,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed24,
          top: 41,
          left: 227,
          width: 27.2,
          height: 22.5,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 15,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 15",
        imageInfoUnselect: {
          image: tooth.unselect15,
          top: 61,
          left: 91,
          width: 27.7,
          height: 21.5,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue15,
          top: 61,
          left: 91,
          width: 27.7,
          height: 21.5,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed15,
          top: 61,
          left: 91,
          width: 27.7,
          height: 21.5,
        },
      },
      {
        teethNo: 25,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 25",
        imageInfoUnselect: {
          image: tooth.unselect25,
          top: 61,
          left: 238,
          width: 27.7,
          height: 21.5,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue25,
          top: 61,
          left: 238,
          width: 27.7,
          height: 21.5,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed25,
          top: 61,
          left: 238,
          width: 27.7,
          height: 21.5,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 16,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 16",
        imageInfoUnselect: {
          image: tooth.unselect16,
          top: 80,
          left: 79,
          width: 31.4,
          height: 33.4,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue16,
          top: 80,
          left: 79,
          width: 31.4,
          height: 33.4,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed16,
          top: 80,
          left: 79,
          width: 31.4,
          height: 33.4,
        },
      },
      {
        teethNo: 26,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 26",
        imageInfoUnselect: {
          image: tooth.unselect26,
          top: 80,
          left: 247,
          width: 31.4,
          height: 33.4,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue26,
          top: 80,
          left: 247,
          width: 31.4,
          height: 33.4,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed26,
          top: 80,
          left: 247,
          width: 31.4,
          height: 33.4,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 17,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 17",
        imageInfoUnselect: {
          image: tooth.unselect17,
          top: 110,
          left: 74,
          width: 26.3,
          height: 29,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue17,
          top: 110,
          left: 74,
          width: 26.3,
          height: 29,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed17,
          top: 110,
          left: 74,
          width: 26.3,
          height: 29,
        },
      },
      {
        teethNo: 27,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 27",
        imageInfoUnselect: {
          image: tooth.unselect27,
          top: 110,
          left: 257.5,
          width: 26.3,
          height: 29,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue27,
          top: 110,
          left: 257.5,
          width: 26.3,
          height: 29,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed27,
          top: 110,
          left: 257.5,
          width: 26.3,
          height: 29,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 18,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 18",
        imageInfoUnselect: {
          image: tooth.unselect18,
          top: 140,
          left: 70,
          width: 25.4,
          height: 24.1,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue18,
          top: 140,
          left: 70,
          width: 25.4,
          height: 24.1,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed18,
          top: 140,
          left: 70,
          width: 25.4,
          height: 24.1,
        },
      },
      {
        teethNo: 28,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 28",
        imageInfoUnselect: {
          image: tooth.unselect28,
          top: 140,
          left: 262.8,
          width: 25.4,
          height: 24.1,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue28,
          top: 140,
          left: 262.8,
          width: 25.4,
          height: 24.1,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed28,
          top: 140,
          left: 262.8,
          width: 25.4,
          height: 24.1,
        },
      },
    ],
  },

  //Teeth Bottom
  {
    teeth: [
      {
        teethNo: 48,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 48",
        imageInfoUnselect: {
          image: tooth.unselect48,
          top: 190,
          left: 72,
          width: 26.6,
          height: 28.1,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue48,
          top: 190,
          left: 72,
          width: 26.6,
          height: 28.1,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed48,
          top: 190,
          left: 72,
          width: 26.6,
          height: 28.1,
        },
      },
      {
        teethNo: 38,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 38",
        imageInfoUnselect: {
          image: tooth.unselect38,
          top: 190,
          left: 262.8,
          width: 26.6,
          height: 28.1,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue38,
          top: 190,
          left: 262.8,
          width: 26.6,
          height: 28.1,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed38,
          top: 190,
          left: 262.8,
          width: 26.6,
          height: 28.1,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 47,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 47",
        imageInfoUnselect: {
          image: tooth.unselect47,
          top: 217,
          left: 81,
          width: 29.8,
          height: 30,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue47,
          top: 217,
          left: 81,
          width: 29.8,
          height: 30,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed47,
          top: 217,
          left: 81,
          width: 29.8,
          height: 30,
        },
      },
      {
        teethNo: 37,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 37",
        imageInfoUnselect: {
          image: tooth.unselect37,
          top: 217,
          left: 253,
          width: 29.8,
          height: 30,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue37,
          top: 217,
          left: 253,
          width: 29.8,
          height: 30,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed37,
          top: 217,
          left: 253,
          width: 29.8,
          height: 30,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 46,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 46",
        imageInfoUnselect: {
          image: tooth.unselect46,
          top: 245,
          left: 92,
          width: 30.9,
          height: 33.1,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue46,
          top: 245,
          left: 92,
          width: 30.9,
          height: 33.1,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed46,
          top: 245,
          left: 92,
          width: 30.9,
          height: 33.1,
        },
      },
      {
        teethNo: 36,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 36",
        imageInfoUnselect: {
          image: tooth.unselect36,
          top: 245,
          left: 242,
          width: 30.9,
          height: 33.1,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue36,
          top: 245,
          left: 242,
          width: 30.9,
          height: 33.1,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed36,
          top: 245,
          left: 242,
          width: 30.9,
          height: 33.1,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 45,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 45",
        imageInfoUnselect: {
          image: tooth.unselect45,
          top: 275,
          left: 107,
          width: 25.3,
          height: 20.9,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue45,
          top: 275,
          left: 107,
          width: 25.3,
          height: 20.9,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed45,
          top: 275,
          left: 107,
          width: 25.3,
          height: 20.9,
        },
      },
      {
        teethNo: 35,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 35",
        imageInfoUnselect: {
          image: tooth.unselect35,
          top: 275,
          left: 236,
          width: 25.3,
          height: 20.9,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue35,
          top: 275,
          left: 236,
          width: 25.3,
          height: 20.9,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed35,
          top: 275,
          left: 236,
          width: 25.3,
          height: 20.9,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 44,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 44",
        imageInfoUnselect: {
          image: tooth.unselect44,
          top: 293,
          left: 118,
          width: 21.7,
          height: 19.6,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue44,
          top: 293,
          left: 118,
          width: 21.7,
          height: 19.6,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed44,
          top: 293,
          left: 118,
          width: 21.7,
          height: 19.6,
        },
      },
      {
        teethNo: 34,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 34",
        imageInfoUnselect: {
          image: tooth.unselect34,
          top: 293,
          left: 227,
          width: 21.7,
          height: 19.6,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue34,
          top: 293,
          left: 227,
          width: 21.7,
          height: 19.6,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed34,
          top: 293,
          left: 227,
          width: 21.7,
          height: 19.6,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 43,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 43",
        imageInfoUnselect: {
          image: tooth.unselect43,
          top: 307,
          left: 133,
          width: 18.6,
          height: 19.6,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue43,
          top: 307,
          left: 133,
          width: 18.6,
          height: 19.6,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed43,
          top: 307,
          left: 133,
          width: 18.6,
          height: 19.6,
        },
      },
      {
        teethNo: 33,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 33",
        imageInfoUnselect: {
          image: tooth.unselect33,
          top: 307,
          left: 216,
          width: 18.6,
          height: 19.6,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue33,
          top: 307,
          left: 216,
          width: 18.6,
          height: 19.6,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed33,
          top: 307,
          left: 216,
          width: 18.6,
          height: 19.6,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 42,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 42",
        imageInfoUnselect: {
          image: tooth.unselect42,
          top: 315,
          left: 150,
          width: 17.3,
          height: 19.7,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue42,
          top: 315,
          left: 150,
          width: 17.3,
          height: 19.7,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed42,
          top: 315,
          left: 150,
          width: 17.3,
          height: 19.7,
        },
      },
      {
        teethNo: 32,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 32",
        imageInfoUnselect: {
          image: tooth.unselect32,
          top: 315,
          left: 200,
          width: 17.3,
          height: 19.7,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue32,
          top: 315,
          left: 200,
          width: 17.3,
          height: 19.7,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed32,
          top: 315,
          left: 200,
          width: 17.3,
          height: 19.7,
        },
      },
    ],
  },
  {
    teeth: [
      {
        teethNo: 41,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 41",
        imageInfoUnselect: {
          image: tooth.unselect41,
          top: 320,
          left: 168,
          width: 15.5,
          height: 19,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue41,
          top: 320,
          left: 168,
          width: 15.5,
          height: 19,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed41,
          top: 320,
          left: 168,
          width: 15.5,
          height: 19,
        },
      },
      {
        teethNo: 31,
        fromDatabase: false,
        fromLocal: false,
        teethName: "Number 31",
        imageInfoUnselect: {
          image: tooth.unselect31,
          top: 320,
          left: 184,
          width: 15.5,
          height: 19,
        },
        imageInfoSelectBlue: {
          image: toothSelectBlue.selectBlue31,
          top: 320,
          left: 184,
          width: 15.5,
          height: 19,
        },
        imageInfoSelectRed: {
          image: toothSelectRed.selectRed31,
          top: 320,
          left: 184,
          width: 15.5,
          height: 19,
        },
      },
    ],
  },
];
